# Generated by Django 4.0.4 on 2022-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1_text', models.CharField(max_length=256)),
                ('choice_2_text', models.CharField(max_length=256)),
            ],
        ),
    ]
