# Generated by Django 4.0.4 on 2022-06-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vote_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='vote_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
