# Generated by Django 4.0.4 on 2022-06-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voted_num',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
    ]
