# Generated by Django 4.0.4 on 2022-06-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_voted_num_choice_votes_choice_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='choice_1_text',
        ),
        migrations.RemoveField(
            model_name='game',
            name='choice_2_text',
        ),
        migrations.RemoveField(
            model_name='game',
            name='vote_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='vote_2',
        ),
    ]
