# Generated by Django 4.0.4 on 2022-06-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_remove_game_choice_1_text_remove_game_choice_2_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.game'),
        ),
    ]
