# Generated by Django 4.0.4 on 2022-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_voted_users_alter_choice_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='votes_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='votes_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
