# Generated by Django 4.0.4 on 2022-07-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_vote_user_vote_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='game',
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.choice'),
        ),
    ]
