# Generated by Django 4.0.4 on 2022-07-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_vote_game_alter_vote_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
    ]
