# Generated by Django 4.0.4 on 2022-07-03 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_vote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='game.choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='side',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
