# Generated by Django 4.0.4 on 2022-07-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_vote_choice_vote_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
    ]
