# Generated by Django 4.0.4 on 2022-07-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_vote_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='game',
        ),
    ]
