# Generated by Django 4.0.4 on 2022-07-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_vote_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='side',
            field=models.BooleanField(default=None),
        ),
    ]
