# Generated by Django 4.0.4 on 2022-07-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_vote_game_alter_vote_choice_alter_vote_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.game'),
        ),
    ]
